version: "3.5"
services:
  isard-dbmon:
    container_name: isard-dbmon
    volumes:
      - "/opt/isard/dbmon:/data"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - isard_network
    image: rethinkdb
    restart: unless-stopped

  isard-nginx:
    container_name: isard-nginx
    volumes:
      - "/opt/isard/certs/default:/etc/nginx/external"
      - "/opt/isard/logs/nginx:/var/log/nginx"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "80:80"
      - "55443:55443"
    networks:
      - isard_network
    image: isard/nginx:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/nginx/Dockerfile    
    restart: unless-stopped

  isard-ui:
    container_name: isard-ui
    volumes:
      #### Source inside (Development)
      - "/opt/src/isard/src:/isard"
      #### Production
      - "/opt/isard/sshkeys:/root/.ssh"
      - "/opt/isard/certs:/certs"
      - "/opt/isard/logs:/isard/logs"
      - "/opt/isard/database/wizard:/isard/install/wizard"
      - "/opt/isard/backups:/isard/backups"
#      - "/opt/isard/uploads:/isard/uploads"
      - "/etc/localtime:/etc/localtime:ro"
#    extra_hosts:
#      - "isard-engine:127.0.0.1"
    networks:
      - isard_network
    env_file:
      - .env
    image: isard/ui:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/ui/Dockerfile
      target: production
    restart: unless-stopped

  isard-grafana:
    environment:
      - ISARD_PUBLIC_DOMAIN=${ISARD_PUBLIC_DOMAIN}
    container_name: isard-grafana
    volumes:
      - "/opt/isard/grafana/grafana/data:/grafana/data"
      - "/opt/isard/grafana/graphite/storage:/opt/graphite/storage"
      - "/opt/isard/grafana/graphite/conf:/opt/graphite/conf"
#    ports:
#      - target: 3000
#        published: 3000
#        protocol: tcp
#        mode: host
    networks:
      - isard_network
    image: isard/grafana:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/grafana/Dockerfile
    restart: unless-stopped

networks:
  isard_network:
    external: false
    name: isard_network
## Uncomment following lines to use different network for
## viewer and Internet connections to desktops
## NOTE: parent should be your viewers network if name
#  internet-vms:
#    driver: macvlan
#    driver_opts:
#      parent: viewers
#    ipam:
#      config:
#        - subnet: 172.30.0.0/16
