version: "3.5"
services:
  isard-hypervisor:
    container_name: isard-hypervisor
    volumes:
      - "/opt/isard/sshkeys/$HOSTNAME:/root/.ssh"
      - "/opt/isard/certs/default:/etc/pki/libvirt-spice"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "2022:22"
      - "5900-6399:5900-6399"
    networks:
      - isard_network
## Uncomment following lines to use different network for
## viewer and Internet connections to desktops
#      - default
#      - internet-vms
    image: isard/hypervisor:${TAG:-latest}
    build:
      context: .
      dockerfile: dockers/hypervisor/Dockerfile    
    privileged: true
    restart: unless-stopped

networks:
  isard_network:
    external: false
    name: isard_network
## Uncomment following lines to use different network for
## viewer and Internet connections to desktops
## NOTE: parent should be your viewers network if name
#  internet-vms:
#    driver: macvlan
#    driver_opts:
#      parent: viewers
#    ipam:
#      config:
#        - subnet: 172.30.0.0/16
